shuwee_admin_default:
    resource: "@ShuweeAdminBundle/Controller/AdminController.php"
    type:     annotation

shuwee_admin_crud:
    resource: .
    type: shuwee_admin_extra

shuwee_admin_section:
    resource: .
    type: shuwee_section_extra