services:
    shuwee_admin:
        class: Wanjee\Shuwee\AdminBundle\Service\AdminManager

    shuwee_admin.routing_loader:
        class: Wanjee\Shuwee\AdminBundle\Routing\Loader\AdminLoader
        arguments: [@shuwee_admin]
        tags:
        - { name: routing.loader }