services:
    #
    shuwee_admin.admin_manager:
        class: Wanjee\Shuwee\AdminBundle\Manager\AdminManager

    shuwee_admin.admin_abstract:
        class: Wanjee\Shuwee\AdminBundle\Admin\Admin
        abstract: true
        calls:
            - [ setContainer, [@service_container]]

    shuwee_admin.routing_helper:
        class: Wanjee\Shuwee\AdminBundle\Routing\Helper\RoutingHelper
        arguments: [@router]

    shuwee_admin.routing_loader:
        class: Wanjee\Shuwee\AdminBundle\Routing\Loader\AdminLoader
        arguments: [@shuwee_admin.admin_manager]
        tags:
            - { name: routing.loader }
            
    shuwee_admin.admin_param_converter:
        class: Wanjee\Shuwee\AdminBundle\Request\ParamConverter\AdminParamConverter
        arguments: [@shuwee_admin.admin_manager]
        tags:
            - { name: request.param_converter }

    shuwee_admin.admin_twig_extension:
        class: Wanjee\Shuwee\AdminBundle\Twig\AdminExtension
        arguments: [@shuwee_admin.admin_manager, @shuwee_admin.routing_helper, @translator]
        public: false
        tags:
            - { name: twig.extension }