services:
    #
    shuwee_admin.admin_manager:
        class: Wanjee\Shuwee\AdminBundle\Service\AdminManager

    shuwee_admin.admin_abstract:
        class: Wanjee\Shuwee\AdminBundle\Admin\Admin
        abstract: true
        calls:
            - [ setContainer, [@service_container]]

    shuwee_admin.routing_helper:
        class: Wanjee\Shuwee\AdminBundle\Routing\Helper\RoutingHelper

    shuwee_admin.routing_loader:
        class: Wanjee\Shuwee\AdminBundle\Routing\Loader\AdminLoader
        arguments: [@shuwee_admin.admin_manager]
        tags:
            - { name: routing.loader }

    shuwee_admin.admin_param_converter:
        class: Wanjee\Shuwee\AdminBundle\Request\ParamConverter\AdminParamConverter
        arguments: [@shuwee_admin.admin_manager]
        tags:
            - { name: request.param_converter }