services:
    # Admin manager
    shuwee_admin.admin_manager:
        class: Wanjee\Shuwee\AdminBundle\Manager\AdminManager

    shuwee_admin.admin_abstract:
        class: Wanjee\Shuwee\AdminBundle\Admin\Admin
        abstract: true
        calls:
            - [ setContainer, [@service_container]]

    # Section manager
    shuwee_admin.section_manager:
        class: Wanjee\Shuwee\AdminBundle\Manager\SectionManager

    shuwee_admin.section_abstract:
        class: Wanjee\Shuwee\AdminBundle\Section\Section
        abstract: true
        calls:
            - [ setContainer, [@service_container]]

    # Routing
    shuwee_admin.admin_routing_helper:
        class: Wanjee\Shuwee\AdminBundle\Routing\Helper\AdminRoutingHelper
        arguments: [@router]

    shuwee_admin.admin_routing_loader:
        class: Wanjee\Shuwee\AdminBundle\Routing\Loader\AdminLoader
        arguments: [@shuwee_admin.admin_manager]
        tags:
            - { name: routing.loader }

    shuwee_admin.section_routing_helper:
        class: Wanjee\Shuwee\AdminBundle\Routing\Helper\SectionRoutingHelper
        arguments: [@router]

    shuwee_admin.section_routing_loader:
        class: Wanjee\Shuwee\AdminBundle\Routing\Loader\SectionLoader
        arguments: [@shuwee_admin.section_manager]
        tags:
            - { name: routing.loader }

    # ParamConverter
    shuwee_admin.admin_param_converter:
        class: Wanjee\Shuwee\AdminBundle\Request\ParamConverter\AdminParamConverter
        arguments: [@shuwee_admin.admin_manager]
        tags:
            - { name: request.param_converter }

    # Twig
    shuwee_admin.admin_twig_extension:
        class: Wanjee\Shuwee\AdminBundle\Twig\AdminExtension
        arguments: [@shuwee_admin.admin_manager, @shuwee_admin.admin_routing_helper, @translator]
        public: false
        tags:
            - { name: twig.extension }

    shuwee_admin.datagrid_twig_extension:
        class: Wanjee\Shuwee\AdminBundle\Twig\DatagridExtension
        arguments: [@translator]
        public: false
        tags:
            - { name: twig.extension }

    # Datagrid
    shuwee_admin.datagrid_manager:
        class: Wanjee\Shuwee\AdminBundle\Datagrid\DatagridManager

    # Datagrid types
    shuwee_admin.datagrid_type_boolean:
        class: Wanjee\Shuwee\AdminBundle\Datagrid\Type\DatagridTypeBoolean
        tags:
            - { name: shuwee.datagrid_type , alias: boolean}

    shuwee_admin.datagrid_type_image:
        class: Wanjee\Shuwee\AdminBundle\Datagrid\Type\DatagridTypeImage
        tags:
            - { name: shuwee.datagrid_type , alias: image}

    shuwee_admin.datagrid_type_text:
        class: Wanjee\Shuwee\AdminBundle\Datagrid\Type\DatagridTypeText
        tags:
            - { name: shuwee.datagrid_type , alias: text}


    # Security
    shuwee_admin.security.user_manager:
        class: Wanjee\Shuwee\AdminBundle\Security\UserManager
        arguments: [@security.encoder_factory, @doctrine.orm.entity_manager]

    shuwee_admin.security.content_voter:
        class:      Wanjee\Shuwee\AdminBundle\Security\Voter\ContentVoter
        arguments: [@shuwee_admin.admin_manager]
        public:     false
        tags:
           - { name: security.voter }

    # Form type extensions
    shuwee_admin.file_preview_type_extension:
        class: Wanjee\Shuwee\AdminBundle\Form\Extension\FilePreviewTypeExtension
        tags:
            - { name: form.type_extension, alias: file }